// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRDVyejuSdrllfNK5hEsx3NJJwK13ztok',
    appId: '1:761834798890:web:0fb6b55c4e3ec8ca492853',
    messagingSenderId: '761834798890',
    projectId: 'holbegram-58c0f',
    authDomain: 'holbegram-58c0f.firebaseapp.com',
    storageBucket: 'holbegram-58c0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC06j-4cAWWYy-ZOxRnRnWhbovTWCvQ4Wg',
    appId: '1:761834798890:android:8a1ba4ec1da9b3ed492853',
    messagingSenderId: '761834798890',
    projectId: 'holbegram-58c0f',
    storageBucket: 'holbegram-58c0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmRlVdY3hXAgtY0BT2Jxr_Mw0wQAm378',
    appId: '1:761834798890:ios:bc4e26bf81bb1fc7492853',
    messagingSenderId: '761834798890',
    projectId: 'holbegram-58c0f',
    storageBucket: 'holbegram-58c0f.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMmRlVdY3hXAgtY0BT2Jxr_Mw0wQAm378',
    appId: '1:761834798890:ios:bc4e26bf81bb1fc7492853',
    messagingSenderId: '761834798890',
    projectId: 'holbegram-58c0f',
    storageBucket: 'holbegram-58c0f.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRDVyejuSdrllfNK5hEsx3NJJwK13ztok',
    appId: '1:761834798890:web:5a1ea2ee09f9d1a0492853',
    messagingSenderId: '761834798890',
    projectId: 'holbegram-58c0f',
    authDomain: 'holbegram-58c0f.firebaseapp.com',
    storageBucket: 'holbegram-58c0f.firebasestorage.app',
  );
}
